# values must have no white space
GREEK_AUTH_ABB = {
    "aesch.": "aeschylus",
    "aeschin.": "aeschines",
    "andoc.": "andocides",
    "antiph.": "antiphon",
    "apoll. dysc.": "apollonius dyscolus",
    "apoll. perg.": "apollonius of perga",
    "apoll. rh.": "apollonius, rhodius",
    "apoll. rhod.": "apollonius, rhodius",
    "aristoph.": "aristophanes",
    "aristot.": "aristotle",
    "athen.": "athenaeus",
    "callim.": "callimachus",
    "dem.": "demosthenes",
    "dio chrys.": "dio",
    "dio chrysostom": "dio",
    "diog. laert.": "diogenes",
    "d.l.": "diogenes",
    "dion. hal.": "dionysius",
    "dionysius of halicarnassus": "dionysius",
    "eur.": "euripides",
    "eustath.": "eustathius",
    "gal.": "galen",
    "hdt.": "herodotus",
    "her.": "herodotus",
    "hes.": "hesiod",
    "hesych.": "hesychius",
    "hh": "homeric hymns",
    "h.h.": "homeric hymns",
    "hippoc.": "hippocrates",
    "hom.": "homer",
    "isae.": "isaeus",
    "isoc.": "isocrates",
    "luc.": "lucian",
    "lys.": "lysias",
    "menand.": "menander",
    "nt": "new testament",
    "n.t.": "new testament",
    "paus.": "pausanias",
    "pind.": "pindar",
    "plat.": "plato",
    "polyb.": "polybius",
    "plut.": "plutarch",
    "sapph.": "sappho",
    "sext. emp.": "sextus",
    "sextus empiricus": "sextus",
    "sext.": "sextus",
    "soph.": "sophocles",
    "strab.": "strabo",
    "theoc.": "theocritus",
    "theocr.": "theocritus",
    "theophr.": "theophrastus",
    "thuc.": "thucydides",
    "tyrt.": "tyrtaeus",
    "xen.": "xenophon",
    "[xen.]": "xenophon",
}


# note: multiword titles have spaces replaced with "_"
# # titles with spaces replaced with "_" are automatically added to WORK_URNS
GREEK_WORK_URNS = {
    "aeschines": {
        "against timarchus": "tlg001",
        "on the embassy": "tlg002",
        "against ctesiphon": "tlg003",
        "epistulae": "tlg004",
    },
    "aeschylus": {
        "suppliant maidens": "tlg001",
        "persians": "tlg002",
        "prometheus bound": "tlg003",
        "seven against thebes": "tlg004",
        "agamemnon": "tlg005",
        "choephoroi": "tlg006",
        "libation bearers": "tlg006",
        "eumenidies": "tlg007",
        "fragmenta": "tlg008",
        "fragmentum": "tlg009",
        "epigrammata": "tlg010",
        "fragmenta (tgf)": "tlg011",
    },
    "andocides": {
        "de mysteriis": "tlg001",
    },
    "antiphon": {
        "against the stepmother for poisoning": "tlg001",
        "first tetralogy": "tlg002",
        "second tetralogy": "tlg003",
        "third tetralogy": "tlg004",
        "on the murder of herodes": "tlg005",
        "on the choreutes": "tlg006",
        "fragmenta": "tlg007",
    },
    "apollonius, rhodius": {
        "argonautica": "tlg001",
        "fragmenta": "tlg002",
        "epigrammata": "tlg003",
    },
    "aristophanes": {
        "acharnians": "tlg001",
        "knights": "tlg002",
        "clouds": "tlg003",
        "wasps": "tlg004",
        "peace": "tlg005",
        "birds": "tlg006",
        "lysistrata": "tlg007",
        "thesmophoriazusae": "tlg008",
        "frogs": "tlg009",
        "ecclesiazusae": "tlg010",
        "plutus": "tlg011",
        "fragmenta": "tlg013",
        "aristophanis cantica": "tlg030",
    },
    "aristotle": {
        "analytica priora et posteriora": "tlg001",
        "on the soul": "tlg002",
        "soul": "tlg002",
        "de anima": "tlg002",
        "de an.": "tlg002",
        "constitution of the athenians": "tlg003",
        "de audibilibus": "tlg004",
        "de caelo": "tlg005",
        "categoriae": "tlg006",
        "de coloribus": "tlg007",
        "de divinatione per somnia (somnium)": "tlg008",
        "ethica eudemia": "tlg009",
        "nicomachean ethics": "tlg010",
        "nic. eth.": "tlg010",
        "epistulae": "tlg011",
        "de generatione animalium": "tlg012",
        "de generatione et corruptione": "tlg013",
        "historia animalium": "tlg014",
        "hist. an.": "tlg014",
        "de incessu animalium": "tlg015",
        "de insomniis": "tlg016",
        "de interpretatione": "tlg017",
        "de iuventute et senectute + de vita et morte": "tlg018",
        "de iuventute et senectute": "tlg018",
        "de vita et morte": "tlg018",
        "de lineis insecabilibus": "tlg019",
        "de longitudine et brevitate vitae": "tlg020",
        "de motu animalium": "tlg021",
        "magna moralia": "tlg022",
        "mechanics": "tlg023",
        "de memoria et reminiscentia": "tlg024",
        "metaphysics": "tlg025",
        "meteorologica": "tlg026",
        "mirabilium auscultationes": "tlg027",
        "de mundo": "tlg028",
        "economics": "tlg029",
        "de partibus animalium": "tlg030",
        "physica": "tlg031",
        "physiognomonica": "tlg032",
        "protrepticus": "tlg033",
        "poetics": "tlg034",
        "politics": "tlg035",
        "problemata": "tlg036",
        "de respiratione": "tlg037",
        "rhetoric": "tlg038",
        "de plantis": "tlg039",  # unclear if this is the right URN
        "sophistici elenchi": "tlg040",
        "de sensu et sensibilibus": "tlg041",
        "de somno et vigilia": "tlg042",
        "de spiritu libellus": "tlg043",
        "topica": "tlg044",
        "de virtibus et vitiis": "tlg045",
        "de ventorum situ et nominibus": "tlg046",
        "de xenophane, de zenone, de gorgia": "tlg047",
        "fragmenta": "tlg049",
        "fragmentum": "tlg050",
        "peplus aristoteleus": "tlg051x01",
        "de plantis alt": "tlg051x02",  # de plantis has this urn in the perseus catalogue, not sure why
        "physicorum libri septimi textus alter": "tlg054",
        "epigrammata demonstrativa": "tlgX04",
    },
    "bion": {
        "epitaphius adonis": "tlg001",
        "epithalamium achillis et deidameiae": "tlg002",
        "fragmenta": "tlg003",
        "idyll.": "idyll",
    },
    "callimachus": {
        "epigrams": "tlg003",
        "epigrams, fragmenta": "tlg004",
        "fragmenta": "tlg005",
        "aetia": "tlg006",
        "iambi": "tlg007",
        "hecale": "tlg009",
        "epigrammata fragmenta": "tlg011",
        "incertae sedis fragmenta": "tlg013",
        "hymn to zeus": "tlg015",
        "zeus": "tlg015",
        "hymn to apollo": "tlg016",
        "apollo": "tlg016",
        "hymn to artemis": "tlg017",
        "artemis": "tlg017",
        "hymn to delos": "tlg018",
        "delos": "tlg018",
        "hymn to athena": "tlg019",
        "athena": "tlg019",
        "hymn to demeter": "tlg020",
        "demeter": "tlg020",
    },
    "demosthenes": {
        "olynthiac 1": "tlg001",
        "olynthiac 2": "tlg002",
        "olynthiac 3": "tlg003",
        "philippic 1": "tlg004",
        "on the peace": "tlg005",
        "philippic 2": "tlg006",
        "on the halonnesus": "tlg007",
        "on the chersonese": "tlg008",
        "philippic 3": "tlg009",
        "philippic 4": "tlg010",
        "reply to philip": "tlg011",
        "philip": "tlg012",
        "on organization": "tlg013",
        "on the navy": "tlg014",
        "on the liberty of the rhodians": "tlg015",
        "for the megalopolitans": "tlg016",
        "on the accession of alexander": "tlg017",
        "on the crown": "tlg018",
        "on the false embassy": "tlg019",
        "against leptines": "tlg020",
        "against midas": "tlg021",
        "against androtion": "tlg022",
        "against aristocrates": "tlg023",
        "against timocrates": "tlg024",
        "against aristogiton 1": "tlg025",
        "against aristogeiton 1": "tlg025",
        "against aristogiton 2": "tlg026",
        "against aristogeiton 2": "tlg026",
        "against aphobus 1": "tlg027",
        "against aphobus 2": "tlg028",
        "against aphobus": "tlg029",
        "against onetor": "tlg030",
        "against onetor 2": "tlg031",
        "against zenothemis": "tlg032",
        "against apatourius": "tlg033",
        "against phormio": "tlg034",
        "against lacritus": "tlg035",
        "for phormio": "tlg036",
        "against pantaenetus": "tlg037",
        "against naisimachus and xenopeithes": "tlg038",
        "against boeotus 1": "tlg039",
        "against boeotus 2": "tlg040",
        "against spudias": "tlg041",
        "against phaenippus": "tlg042",
        "against macartatus": "tlg043",
        "against leochares": "tlg044",
        "against stephanus 1": "tlg045",
        "against stephanus 2": "tlg046",
        "against evergus and mnesibulus": "tlg047",
        "against olympiodorus": "tlg048",
        "against timotheus": "tlg049",
        "against polycles": "tlg050",
        "on the trierarchic crown": "tlg051",
        "against callipus": "tlg052",
        "against nicostratus": "tlg053",
        "against conon": "tlg054",
        "against callicles": "tlg055",
        "against dionysodorus": "tlg056",
        "against eubulides": "tlg057",
        "against theocrines": "tlg058",
        "against neaera": "tlg059",
        "funeral speech": "tlg060",
        "erotic essay": "tlg061",
        "exordia": "tlg062",
        "letters": "tlg063",
    },
    "dionysius": {
        "antiquitates romanae": "tlg001",
        "de antiquis oratoribus": "tlg002",
    },
    "euripides": {
        "cyclops": "tlg001",
        "alcestis": "tlg002",
        "medea": "tlg003",
        "heraclidae": "tlg004",
        "heraclid.": "tlg004",
        "hippolytus": "tlg005",
        "andromache": "tlg006",
        "hecuba": "tlg007",
        "suppliants": "tlg008",
        "supplices": "tlg008",
        "heracles": "tlg009",
        "ion": "tlg010",
        "trojan women": "tlg011",
        "trojades": "tlg011",
        "troiades": "tlg011",
        "electra": "tlg012",
        "iphigeneia in taurus": "tlg013",
        "iphigeneia in tauris": "tlg013",
        "helen": "tlg014",
        "phoenician women": "tlg015",
        "orestes": "tlg016",
        "bacchae": "tlg017",
        "iphigeneia in aulis": "tlg018",
        "rhesus": "tlg019",
        "fragmenta (tgf)": "tlg020",
        "fragmenta papyacea. cretum": "tlg021",
        "epinicium in alcibiadem": "tlg022",
        "fragments phaethontis": "tlg023",
        "fragmenta alexandri": "tlg025",
        "hypsiples fragmenta": "tlg026",
        "fragmenta phrixei": "tlg027",
        "fragmenta fabulae incertae": "tlg028",
        "fragmenta oenei": "tlg030",
        "epigrammata": "tlg031",
    },
    "galen": {
        "discourses": "tlg001",
        "de temperamentis": "tlg009",
        "de naturalibus facultatibus": "tlg010",
    },
    "hesiod": {
        "theogony": "tlg001",
        "works and days": "tlg002",
        "shield of heracles": "tlg003",
        "fragmenta": "tlg004",
        "testimonia": "tlg005",
        "fragmenta astronomica": "tlg006",
    },
    "hippocrates": {
        "de prisca medicina": "tlg001",
        "de aere aquis et locis": "tlg002",
        "prognosticon": "tlg003",
        "de diaeta in morbis acutis": "tlg004",
        "de diaeta acutorum": "tlg005",
        "de morbis popularibus": "tlg006",
        "de capitis vulneribus": "tlg007",
        "de officina medici": "tlg008",
        "de fracturis": "tlg009",
        "de articulis": "tlg010",
        "vectiarius": "tlg011",
        "aphorismi": "tlg012",
        "jusjurandum": "tlg013",
        "lex": "tlg014",
        "de morbo sacro": "tlg027",
        "de ulceribus": "tlg028",
        "de haemorrhoidibus": "tlg029",
        "de fistulis": "tlg030",
        "de alimento": "tlg046",
        "praeceptiones": "tlg051",
        "epistulae": "tlg055",
    },
    "homer": {"iliad": "tlg001", "odyssey": "tlg002", "epigrammata": "tlg003"},
    "homeric hymns": {
        "hymn 1 to dionysus": "tlg001",
        "dionysus": "tlg001",
        "hymn 2 to demeter": "tlg002",
        "demeter": "tlg002",
        "hymn 3 to apollo": "tlg003",
        "apollo": "tlg003",
        "hymn 4 to hermes": "tlg004",
        "hermes": "tlg004",
        "hymn 5 to aphrodite": "tlg005",
        "hymn 6 to aphrodite": "tlg006",
        "hymn 7 to dionysus": "tlg007",
        "hymn 8 to ares": "tlg008",
        "hymn 9 to artemis": "tlg009",
        "hymn 10 to aphrodite": "tlg010",
        "hymn 11 to athena": "tlg011",
        "athena": "tlg011",
        "hymn 12 to hera": "tlg012",
        "hera": "tlg012",
        "hymn 13 to demeter": "tlg013",
        "hymn 14 to the mother of the gods": "tlg014",
        "mother of the gods": "tlg014",
        "hymn 15 to heracles": "tlg015",
        "heracles": "tlg015",
        "hymn 16 to asclepius": "tlg016",
        "asclepius": "tlg016",
        "hymn 17 to the dioscuri": "tlg017",
        "dioscuri": "tlg017",
        "hymn 18 to hermes": "tlg018",
        "hymn 19 to pan": "tlg019",
        "pan": "tlg019",
        "hymn 20 to hephaestus": "tlg020",
        "hephaetus": "tlg020",
        "hymn 21 to apollo": "tlg021",
        "hymn 22 to poseidon": "tlg022",
        "poseidon": "tlg022",
        "hymn 23 to zeus": "tlg023",
        "zeus": "tlg023",
        "hymn 24 to hestia": "tlg024",
        "hestia": "tlg024",
        "hymn 25 to the muses and apollo": "tlg025",
        "hymn 26 to dionysus": "tlg026",
        "hymn 27 to artemis": "tlg027",
        "hymn 28 to athena": "tlg028",
        "hymn 29 to hestia": "tlg029",
        "hymn 30 to earth": "tlg030",
        "hymn 31 to helios": "tlg031",
        "helios": "tlg031",
        "hymn to selene": "tlg032",
        "selene": "tlg032",
        "hymn 33 to the dioscuri": "tlg033",
    },
    "isaeus": {
        "apollodorus": "tlg007",
    },
    "isocrates": {
        "ad alexandrum": "tlg028",
        "helen": "tlg009",
        "ad timotheum": "tlg026",
        "letter 7": "tlg026",
    },
    "lucian": {
        "hippias": "tlg002",
        "symposium": "tlg015",
        "iuppiter trageodeus": "tlg018",
        "juppiter trageodeus": "tlg018",
        "iupp. trag.": "tlg018",
        "jupp. trag.": "tlg018",
        "icaromenippus": "tlg021",
        "dialogi mortuorum": "tlg066",
        "dial. mort.": "tlg066",
        "dialogi deorum": "tlg068",
        "dial. deor.": "tlg068",
        "dial. d.": "tlg068",
    },
    "lysias": {
        "against eratosthenes": "tlg012",
    },
    "menander": {
        "dyscolus": "tlg007",
        "sententiae e codicibus byzantinis": "tlg042",
        "sententiae": "tlg024",
        "samia": "tlg029",
    },
    "new testament": {
        "matthew": "tlg001",
        "mark": "tlg002",
        "luke": "tlg003",
        "john": "tlg004",
        "acts": " tlg005",
        "romans": "tlg006",
        "1 corinthians": "tlg007",
        "2 corinthians": "tlg008",
        "galatians": "tlg009",
        "ephesians": "tlg010",
        "philippians": "tlg011",
        "colossians": "tlg012",
        "1 thessalonians": "tlg013",
        "2 thessalonians": "tlg014",
        "1 timothy": "tlg015",
        "2 timothy": "tlg016",
        "titus": "tlg017",
        "philemon": "tlg018",
        "hebrews": "tlg019",
        "james": "tlg020",
        "1 peter": "tlg021",
        "2 peter": "tlg022",
        "1 john": "tlg023",
        "2 john": "tlg024",
        "3 john": "tlg025",
        "jude": "tlg026",
        "revelation": "tlg027",
    },
    "pindar": {
        "olympia": "tlg001",
        "pythia": "tlg002",
        "nemea": "tlg003",
        "isthmea": "tlg004",
        "fragmenta": "tlg005",
    },
    "plato": {
        "euthyphro": "tlg001",
        "euthyph.": "tlg001",
        "apology": "tlg002",
        "crito": "tlg003",
        "phaedo": "tlg004",
        "cratylus": "tlg005",
        "theaetetus": "tlg006",
        "sophist": "tlg007",
        "statesman": "tlg008",
        "parmenides": "tlg009",
        "philebus": "tlg010",
        "symposium": "tlg011",
        "phaedrus": "tlg012",
        "alcibiades 1": "tlg013",
        "alc. 1": "tlg013",
        "alcibiades 2": "tlg014",
        "alc. 2": "tlg014",
        "hipparchus": "tlg015",
        "lovers": "tlg016",
        "theages": "tlg017",
        "charmides": "tlg018",
        "laches": "tlg019",
        "lysis": "tlg020",
        "euthydemus": "tlg021",
        "protagoras": "tlg022",
        "gorgias": "tlg023",
        "meno": "tlg024",
        "greater hippias": "tlg025",
        "hippias major": "tlg025",
        "hipp. maj.": "tlg025",
        "lesser hippias": "tlg026",
        "hippias minor": "tlg026",
        "hippias min.": "tlg026",
        "hipp. min.": "tlg026",
        "ion": "tlg027",
        "menexenus": "tlg028",
        "cleitophon": "tlg029",
        "republic": "tlg030",
        "timaeus": "tlg031",
        "critias": "tlg032",
        "minos": "tlg033",
        "laws": "tlg34",
        "legg.": "tlg34",
        "epinomis": "tlg035",
        "letters": "tlg036",
        "definitiones": "tlg037",
        "spuria": "tlg038",
        "eryxias": "tlg038",
        "axiochus": "tlg038",
        "epigrammata": "tlg039",
    },
    "plutarch": {
        "theseus": "tlg001",
        "romulus": "tlg002",
        "comparison of theseus and romulus": "tlg003",
        "lycurgus": "tlg004",
        "numa": "tlg005",
        "comparison of lycurgus and numa": "tlg006",
        "solon": "tlg007",
        "publicola": "tlg008",
        "comparison of solon and publicola": "tlg009",
        "themistocles": "tlg010",
        "camillus": "tlg011",
        "pericles": "tlg012",
        "fabius maximus": "tlg013",
        "comparison of pericles and fabius maximus": "tlg014",
        "alcibiades": "tlg015",
        "caius marcius coriolanus": "tlg016",
        "coriolanus": "tlg016",
        "comparison of alcibiades and coriolanus": "tlg017",
        "timoleon": "tlg018",
        "aemilius paullus": "tlg019",
        "comparison of timoleon and aemilius": "tlg020",
        "pelopidas": "tlg021",
        "marcellus": "tlg022",
        "comparison of pelopidas and marcellus": "tlg023",
        "aristeides": "tlg024",
        "marcus cato": "tlg025",
        "cato": "tlg025",
        "comparison of aristides with marcus cato": "tlg026",
        "philopoemen": "tlg027",
        "titus flamininus": "tlg028",
        "comparison of philopoemen and titus": "tlg029",
        "pyrrhus": "tlg030",
        "caius marius": "tlg031",
        "marius": "tlg031",
        "lysander": "tlg032",
        "sulla": "tlg033",
        "comparison of lysander and sulla": "tlg034",
        "cimon": "tlg035",
        "lucullus": "tlg036",
        "comparison of lucullus and cimon": "tlg037",
        "nicias": "tlg038",
        "crassus": "tlg039",
        "comparison of nicias and crassus": "tlg040",
        "eumenes": "tlg041",
        "sertorius": "tlg042",
        "comparison of sertorius and eumenes": "tlg043",
        "agesilaus": "tlg044",
        "pompey": "tlg045",
        "comparison of agesilaus and pompey": "tlg046",
        "alexander": "tlg047",
        "caesar": "tlg048",
        "phocion": "tlg049",
        "cato minor": "tlg050",
        "agis et cleomenes": "tlg051",
        "agis": "tlg051a",
        "cleomenes": "tlg051b",
        "tiberius et gaius gracchus": "tlg052",
        "tiberius gracchus": "tlg052a",
        "tib. gracch.": "tlg052a",
        "caius gracchus": "tlg052b",
        "comparison of agis and cleomenes and the gracchi": "tlg053",
        "demosthenes": "tlg054",
        "dem.": "tlg054",
        "cicero": "tlg055",
        "comparison of demosthenes with cicero": "tlg056",
        "demetrius": "tlg057",
        "antonius": "tlg058",
        "comparison of demetrius and antony": "tlg059",
        "dion": "tlg060",
        "brutus": "tlg061",
        "comparison of dion and brutus": "tlg062",
        "aratus": "tlg063",
        "artaxerxes": "tlg064",
        "galba": "tlg065",
        "otho": "tlg066",
        "de liberis educandis": "tlg067",
        "quomodo adolescens poetas audire debeat": "tlg068",
        "de recta ratione audiendi": "tlg069",
        "quomodo adulator ab amico internoscatur": "tlg070",
        "quomodo quis suos in virtute sentiat profectus": "tlg071",
        "de capienda ex inimicis utilitate": "tlg072",
        "de amicorum multitudine": "tlg073",
        "de fortuna": "tlg074",
        "de virtute et vitio": "tlg075",
        "consolatio ad apollonium": "tlg076",
        "de tuenda sanitate praecepta": "tlg077",
        "conjugalia praecepta": "tlg078",
        "septem sapientium convivium": "tlg079",
        "de superstitione": "tlg080",
        "regum et imperatorum apophthegmata": "tlg081",
        "apophthegmata laconica": "tlg082",
        "instituta laconica": "tlg082a",
        "lacaenarum apophthegmata": "tlg082b",
        "mulierum virtutes": "tlg083",
        "aetia romana et graeca": "tlg084",
        "quaestiones romanae": "tlg084a",
        "quaestiones graecae": "tlg084b",
        "parallela minora": "tlg085",
        "de fortuna romanorum": "tlg086",
        "de alexandri magni fortuna aut virtute": "tlg087",
        "de gloria atheniensium": "tlg088",
        "de iside et osiride": "tlg089",
        "de iside": "tlg089",
        "de e apud delphos": "tlg090",
        "de pythiae oraculis": "tlg091",
        "de defectu oraculorum": "tlg092",
        "an virtus doceri possit": "tlg093",
        "de virtute morali": "tlg094",
        "de cohibenda ira": "tlg095",
        "de tranquilitate animi": "tlg096",
        "de fraterno amore": "tlg097",
        "de amore prolis": "tlg098",
        "an vitiositas ad infelicitatem sufficia": "tlg099",
        "animini an corporis affectiones sint peiores": "tlg100",
        "de garrulitate": "tlg101",
        "de curiositate": "tlg102",
        "de cupiditate divitiarum": "tlg103",
        "de vitioso pudore": "tlg104",
        "de invidia et odio": "tlg105",
        "de se ipsum citra invidiam laudando": "tlg106",
        "de sera numinis vindicta": "tlg107",
        "de fato": "tlg108",
        "de genio socratis": "tlg109",
        "de exilio": "tlg110",
        "consolatio ad uxorem": "tlg111",
        "quaestiones convivales": "tlg112",
        "amatorius": "tlg113",
        "amatoriae narrationes": "tlg114",
        "maxime cum principibus philosopho esse diserendum": "tlg115",
        "ad principem ineruditum": "tlg116",
        "praecepta gerendae reipublicae": "tlg118",
        "praecepta": "tlg118",
        "de unius in republica dominatione": "tlg119",
        "de vitando aere alieno": "tlg120",
        "vitae decem oratorum": "tlg121",
        "comparationis aristophanis et menandri compendium": "tlg122",
        "de herodoti malignitate": "tlg123",
        "quaestiones naturales": "tlg125",
        "de faciae quae in orbe lunae apparet": "tlg126",
        "de primo frigido": "tlg127",
        "aquane an ignis sit utilior": "tlg128",
        "de sollertia animalium": "tlg129",
        "bruta animalia ratione uti": "tlg130",
        "de esu carnium I": "tlg131",
        "de esu carnium II": "tlg132",
        "platonicae quaestiones": "tlg133",
        "de animae procreatione in timaeo": "tlg134",
        "epitome libri de animae procreatione in timaeo": "tlg135",
        "de stoicorum repugnantiis": "tlg136",
        "compendium argumenti stoicos absurdiora poetis dicere": "tlg137",
        "de communibus notitiis adversus stoicos": "tlg138",
        "non posse suaviter vivi secundum epicurum": "tlg139",
        "adversus colotem": "tlg140",
        "an recte dicum sit latenter esse vivendum": "tlg141",
        "parsne an facultas animi sit viva passiva": "tlg144",
        "fragmenta": "tlg145",
        "ἐκλογὴ περὶ τῶν ἀδυνάτων": "tlg147",
        "moralia": "moralia",
    },
    "sappho": {
        "fragmenta": "tlg001",
        "epigrammata": "tlg002",
    },
    "sextus": {
        "pyrrhoniae hypotyposes": "tlg001",
        "adversus mathematicos": "tlg002",
        "adv. math.": "tlg002",
    },
    "sophocles": {
        "trachiniae": "tlg001",
        "antigone": "tlg002",
        "ajax": "tlg003",
        "oedipus tyrannus": "tlg004",
        "oedipus rex": "tlg004",
        "electra": "tlg005",
        "philoctetes": "tlg006",
        "oedipus at colonus": "tlg007",
        "oedipus coloneus": "tlg007",
        "ichneutai": "tlg008",
        "fragmenta (elegiaca)": "tlg009",
    },
    "theocritus": {
        "idylls": "tlg001",
        "epigrams": "tlg002",
    },
    "theophrastus": {
        "historia plantarum": "tlg001",
        "de causis plantarum": "tlg002",
        "de sensu et sensibilibus": "tlg003",
        "de lapidibus": "tlg004",
        "de igne": "tlg005",
        "metaphysica": "tlg006",
        "characters": "tlg009",
        "de odoribus": "tlg010x01",
        "de ventis": "tlg010x02",
        "de signis tempestum": "tlg010x03",
        "de lassitudine": "tlg010x04",
        "de vertigine": "tlg010x05",
        "de sudore": "tlg010x06",
        "de animi defectione": "tlg010x07",
        "de nervorum resolutione": "tlg010x08",
        "fragmenta": "tlg010",
    },
    "thucydides": {
        "history of the peloponnesian war": "tlg001",
        "epigramma": "tlg002",
    },
    "xenophon": {  # note: epistles have different auth urn
        "hellenica": "tlg001",
        "memorabilia": "tlg002",
        "economics": "tlg003",
        "symposium": "tlg004",
        "apology": "tlg005",
        "anabasis": "tlg006",
        "cyropedia": "tlg007",
        "hiero": "tlg008",
        "agesilaus": "tlg009",
        "constitution of the lacedaimonians": "tlg010",
        "ways and means": "tlg011",
        "on the cavalry commander": "tlg012",
        "on the art of horsemanship": "tlg013",
        "on hunting": "tlg014",
        "constitution of the athenians": "tlg015",
        "const. ath.": "tlg015",
        "resp. athen.": "tlg015",
    },
}

# surely the more general point is that if there is no work name then the ref should resolve to tlg001

GREEK_SINGLE_WORK_AUTHORS = {
    "apollonius of perga",
    "athenaeus",
    "dio",
    "diogenes",  # laertius
    "eustathius",
    "herodotus",
    "hesychius",  # the grammarian
    "pausanias",
    "polybius",
    "strabo",
    "tyrtaeus",
}

GREEK_AUTH_URNS = {
    "apollonius, rhodius": "urn:cts:greekLit:tlg0001",
    "thucydides": "urn:cts:greekLit:tlg0003",
    "theocritus": "urn:cts:greekLit:tlg0005",
    "euripides": "urn:cts:greekLit:tlg0006",
    "plutarch": "urn:cts:greekLit:tlg0007",
    "athenaeus": "urn:cts:greekLit:tlg0008",
    "sappho": "urn:cts:greekLit:tlg0009",
    "isocrates": "urn:cts:greekLit:tlg0010",
    "sophocles": "urn:cts:greekLit:tlg0011",
    "homer": "urn:cts:greekLit:tlg0012",
    "homeric hymns": "urn:cts:greekLit:tlg0013",
    "demosthenes": "urn:cts:greekLit:tlg0014",
    "diogenes": "urn:cts:greekLit:tlg0004",
    "herodotus": "urn:cts:greekLit:tlg0016",
    "isaeus": "urn:cts:greekLit:tlg0017",
    "aristophanes": "urn:cts:greekLit:tlg0019",
    "hesiod": "urn:cts:greekLit:tlg0020",
    "aeschines": "urn:cts:greekLit:tlg0026",
    "andocides": "urn:cts:greekLit:tlg0027",
    "antiphon": "urn:cts:greekLit:tlg0028",
    "new testament": "urn:cts:greekLit:tlg0031",
    "xenophon": "urn:cts:greekLit:tlg0032",
    "pindar": "urn:cts:greekLit:tlg0033",
    "bion": "urn:cts:greekLit:tlg0036",
    "galen": "urn:cts:greekLit:tlg0057",
    "plato": "urn:cts:greekLit:tlg0059",
    "lucian": "urn:cts:greekLit:tlg0062",
    "dionysius": "urn:cts:greekLit:tlg0081",
    "aeschylus": "urn:cts:greekLit:tlg0085",
    "aristotle": "urn:cts:greekLit:tlg0086",
    "theophrastus": "urn:cts:greekLit:tlg0093",
    "strabo": "urn:cts:greekLit:tlg0099",
    "tyrtaeus": "urn:cts:greekLit:tlg0266",
    "pausanias": "urn:cts:greekLit:tlg0525",
    "callimachus": "urn:cts:greekLit:tlg0533",
    "lysias": "urn:cts:greekLit:tlg0540",
    "menander": "urn:cts:greekLit:tlg0541",
    "polybius": "urn:cts:greekLit:tlg0543",
    "sextus": "urn:cts:greekLit:tlg0544",
    "dio": "urn:cts:greekLit:tlg0612",
    "hippocrates": "urn:cts:greekLit:tlg0627",
    "eustathius": "urn:cts:greekLit:tlg4083",
    "hesychius": "urn:cts:greekLit:hesychius",  # placeholder urn since none has been minted
}
