# values must have no white space
LATIN_AUTH_ABB = {
    "caes.": "caesar",
    "cic.": "cicero",
    "lucr.": "lucretius",
    "prop.": "propertius",
    "propert.": "propertius",
    "ov.": "ovid",
    "plaut.": "plautus",
    "tac.": "tacitus",
    "verg.": "vergil",
}


# note: multiword titles have spaces replaced with "_"
# # titles with spaces replaced with "_" are automatically added to WORK_URNS
LATIN_WORK_URNS = {
    "caesar": {
        "gallic war": "phi001",
        "civil war": "phi002",
        "fragmenta": "phi004",
        "carmina": "phi006",
    },
    "cicero": {
        "for publius quinctius": "phi001",
        "for sextus roscius of ameria": "phi002",
        "for quintus roscius the actor": "phi003",
        "divinatio against q. caecilius": "phi004",
        "against verres": "phi005",
        "for marcus tullius": "phi006",
        "for marcus fonteius": "phi007",
        "for aulus caecina": "phi008",
        "on pompey's command": "phi009",
        "for aulus cluentius": "phi010",
        "on the agrarian law": "phi011",
        "for rabirius on a charge of treason": "phi012",
        "against catiline": "phi013",
        "in catilinam": "phi013",
        "for lucius murena": "phi014",
        "pro murena": "phi014",
        "for sulla": "phi015",
        "for archias": "phi016",
        "pro archia": "phi016",
        "for flaccus": "phi017",
        "pro flacco": "phi017",
        "to the citizens after his return": "phi018",
        "in the senate after his return": "phi019",
        "on his house": "phi020",
        "on the responses of the haruscpices": "phi021",
        "for sestius": "phi022",
        "against vatinius": "phi023",
        "for marcus caelius": "phi024",
        "on the consular provinces": "phi025",
        "for cornelius balbus": "phi026",
        "against piso": "phi027",
        "for plancius": "phi028",
        "for rabirius postumus": "phi030",
        "for marcellus": "phi032",
        "for aemilius scaurus": "phi029",
        "for milo": "phi031",
        "pro milone": "phi031",
        "for ligarius": "phi033",
        "for king deiotarius": "phi034",
        "philippics": "phi035",
        "de inventione": "phi036",
        "on oratory": "phi037",
        "partitiones oratoriae": "phi038",
        "brutus": "phi039",
        "orator": "phi040",
        "de optimo genere opratorum": "phi041",
        "topica": "phi042",
        "de republica": "phi043",
        "de legibus": "phi044",
        "academica": "phi045",
        "lucullus": "phi046",
        "paradoxa stoicum": "phi047",
        "de finibus bonorum et malorum": "phi048",
        "tusculanae disputationes": "phi039",
        "de natura deorum": "phi050",
        "de senectute": "phi051",
        "de amicitia": "phi052",
        "de divinatione": "phi053",
        "de fato": "phi054",
        "de officiis": "phi055",
        "letters to his friends": "phi056",
        "epistulae ad familiares": "phi056",
        "letters to atticus": "phi057",
        "ad atticum": "phi057",
        "letters to his brother quintus": "phi058",
        "letters to brutus": "phi059",
        "arati phaenomena": "phi060",
        "facete dicta": "phi061",
        "carmina": "phi62",
        "ex iliade": "phi62x01",
        "ex odyssea": "phi62x02",
        "ex aeschyli": "phi62x03",
        "ex sophoclis": "phi62x04",
        "ex euripidis": "phi62x05",
        "alcyones": "phi62x06",
        "limon": "phi62x07",
        "marius": "phi62x08",
        "ad caesarem de expeditione brittanica": "phi62x09",
        "elegia talemastis": "phi62x10",
        "epigrammata": "phi62x11",
        "commentarii causarum": "phi063",
        "fragmenta epistularum": "phi064",
        "hortensius": "phi065",
        "fragmenta librorum incertorum": "phi066",
        "singulae voces ex incertis libris": "phi066x02",
        "de iure civili in artem redigendo": "phi067",
        "cum quaestor lilybaeo decederet": "phi68x01",
        "pro l. vareno": "phi68x02",
        "pro oppio": "phi68x03",
        "pro c. manilio": "phi68x04",
        "pro c. fundanio": "phi68x05",
        "pro q. gallio": "phi6806",
        "pro cornelio": "phi68x07",
        "in toga candida": "phi68x09",
        "cum a ludis contionem avocavit": "phi68x10",
        "de proscriptorum liberis": "phi68x11",
        "contra contionem q. metelli": "phi68x12",
        "in p. clodium et c. curionem": "phi68x13",
        "interrogatio de aere alieno milonis": "phi68x14",
        "de rege alexandrino": "phi68x15",
        "pro p. vatinio": "phi68x16",
        "pro negotiatoribus achaeis": "phi68x17",
        "oratio pridie quam in exilium iret": "phi68x18",
        "incertorum oratorum fragmenta": "phi069",
        "oeconomicus": "phi70x01",
        "de auguriis": "phi70x03",
        "porciae laudatio": "phi70x05",
        "de gloria": "phi70x06",
        "cato": "phi70x04",
        "consolatio": "phi70x07",
        "de consiliis suis": "phi70x08",
        "de virtutibus": "phi70x09",
        "de chorographia": "phi70x10",
        "admiranda": "phi70x11",
        "arati prognostica": "phi071",
        "timaeus": "phi072",  # this also has stoa061
        "rhetorica ad herennium [sp.]": "phi073",
        "in sallustium [sp.]": "phi074",
        "epistula ad octavianum [sp.]": "phi075",
        "de consolatu suo": "stoa007",  # note that the author urn for this in the catalog is stoa0087
        "somnium scipionum": "stoa060a",  # same here and below
    },
    "lucretius": {
        "de rerum natura": "phi001",
    },
    "ovid": {
        "amores": "phi001",
        "epistulae": "phi002",
        "medicamina faciei femineae": "phi003",
        "amatoria": "phi004",
        "remedia amoris": "phi005",
        "metamorphoses": "phi006",
        "fasti": "phi007",
        "tristia": "phi008",
        "ex ponto": "phi009",
        "epistulae ex ponto": "phi009",
        "ibis": "phi010",
        "medea": "phi011",
        "carmina; fragmenta": "phi012",
        "nux [sp.]": "phi013",
        "halieutica [sp.]": "phi014",
        "consolatio ad liviam (epicedion drusi)": "phi015",
    },
    "plautus": {
        "trinummus": "phi019",
    },
    "propertius": {
        "elegies": "tlg001",
    },
    "tacitus": {
        "agricola": "phi001",
        "germania": "phi002",
        "dialogus": "phi003",
        "historiae": "phi004",
        "annales": "phi005",
    },
    "vergil": {
        "eclogues": "phi001",
        "georgics": "phi002",
        "aeneid": "phi003",
    },
}

# surely the more general point is that if there is no work name then the ref should resolve to tlg001

LATIN_SINGLE_WORK_AUTHORS = {"lucretius", "propertius"}

LATIN_AUTH_URNS = {
    "caesar": "urn:cts:latinLit:phi0448",
    "cicero": "urn:cts:latinLit:phi0474",
    "ovid": "urns:cts:latinLit:phi0959",
    "lucretius": "urn:cts:latinLit:phi0550",
    "plautus": "urn:cts:latinLit:phi0119",
    "propertius": "urn:cts:latinLit:phi0620",
    "tacitus": "urn:cts:latinLit:phi1351",
    "vergil": "urn:cts:latinLit:phi0690",
}
